# test the synchrotron module
from agnpy.emission_regions import Cone
import astropy.units as u
from agnpy.spectra import ParticleDistribution
from agnpy.utils.conversion import nu_to_epsilon_prime, B_to_cgs, lambda_c_e, mec2
from agnpy.spectra.spectra import ExpCutoffPowerLaw
from agnpy.synchrotron import *
from scipy.interpolate import interp1d
from scipy.integrate import cumulative_trapezoid
from agnpy.synchrotron.base_synchrotron import Synchrotron
import numpy as np
from astropy.constants import c, sigma_T, m_e, e, mu0

# e = e.gauss
mec2 = mec2.to("eV")
import matplotlib.pyplot as plt
import numpy as np
import astropy.units as u
from astropy.constants import m_e
from astropy.coordinates import Distance
from agnpy.utils.conversion import nu_to_epsilon_prime, B_to_cgs, lambda_c_e, mec2
import pytest
from pathlib import Path
from agnpy.emission_regions import Blob
from agnpy.spectra import ExpCutoffPowerLaw
from agnpy.synchrotron import Synchrotron, nu_synch_peak
from agnpy.utils.math import trapz_loglog

mec2 = mec2.to("eV")

from agnpy.utils.validation_utils import (
    make_comparison_plot,
    extract_columns_sample_file,
    check_deviation,
    clean_and_make_dir,
)

agnpy_dir = Path(__file__).parent.parent.parent  # go to the agnpy root
# where to read sampled files
data_dir = agnpy_dir / "data"
# where to save figures, clean-up before making the new
figures_dir = clean_and_make_dir(agnpy_dir, "crosschecks/figures/synchrotron")

# Parameters used in Table 1 of Potter and Cotter; Fitting BL Lac (abdo et al. 2011)
z = 0.0686
B_o = (3.63 * 1e-5 * u.T).to(u.G)
u_B = ((B_to_cgs(B_o) ** 2) / (8 * np.pi)).to("erg cm-3")
R_o = 7.32 * 1e15 * u.cm
W_j = 7.63 * 1e36 * u.W
L = 100 * u.pc
theta_open = 9.7 * u.deg
Gamma = 12
theta_s = 2 * u.deg
A_equi = 1.0
# Electron Distribution imposed by Potter and Cotter
p = 2
gamma_minimum = (5.11 * 1e6 * u.eV / mec2.to("eV")).value
gamma_c = (5.6 * 1e9 * u.eV / mec2.to("eV")).value
n_e = ExpCutoffPowerLaw(
    k=1,
    mass=m_e,
    p=p,
    gamma_min=gamma_minimum,
    gamma_max=100 * gamma_c,
    gamma_c=gamma_c,
)


class TestConeSynchrotron:
    @pytest.mark.parametrize(
        "file_ref, n_e, figure_title, figure_path",
        [
            (
                f"{data_dir}/reference_seds/cotter_potter/fig3b_paperI/synchrotron.txt",
                n_e,
                "Cone SSA ECPL",
                f"{figures_dir}/cone_ssa_ecpl.png",
            ),
        ],
    )
    def test_ssa_reference_sed(
        self,
        file_ref,
        n_e,
        figure_title,
        figure_path,
    ):
        """Test SSA SED generated by a given electron distribution against the
        ones generated with jetset version 1.1.2, via jetset_ssa_sed.py script."""
        # reference SED
        nu_ref, sed_ref = extract_columns_sample_file(file_ref, "Hz", "erg cm-2 s-1")

        # same parameters used to produce the jetset SED
        jet = Cone.from_jet_power(
            W_j=W_j,
            B_o=B_o,
            L=L,
            n_e=n_e,
            theta=theta_open,
            Gamma=Gamma,
            x_size=100,
            gamma_e_size=1000,
            z=z,
            delta_D=20.39,
            electron_escape=True,
            escape_coefficient=2.75,
        )
        # recompute the SED at the same ordinates where the figure was sampled
        synch = Synchrotron(jet, ssa=True)
        synch.flux_obs(nu_ref)
        synch.evaluate_attenuation()
        sed_agnpy = synch.sed_flux(nu_ref, ssa=True)

        # sed comparison plot, we will check between 10^(11) and 10^(19) Hz
        nu_range = [1e12, 3.36e17] * u.Hz
        make_comparison_plot(
            nu_ref,
            sed_agnpy,
            sed_ref,
            "agnpy",
            "CnP-Paper I: Fig 3b",
            figure_title,
            figure_path,
            "sed",
            comparison_range=nu_range.to_value("Hz"),
        )

        # requires that the SED points deviate less than 5% from the figure
        assert check_deviation(nu_ref, sed_agnpy, sed_ref, 0.25, nu_range)
